
default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  adapter: postgresql
  encoding: unicode
  database: field_booker_development
  pool: 5
  username: admin3
  password: 'password'



